"""empty message

Revision ID: 20bdf044c7ae
Revises: 
Create Date: 2023-10-24 08:45:16.222349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bdf044c7ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dailyHabit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dailyHabit_id'], ['daily_habits.id'], name=op.f('fk_entries_dailyHabit_id_daily_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('users')
    op.drop_table('daily_habits')
    # ### end Alembic commands ###
