"""empty message

Revision ID: e19c8ff94028
Revises: 
Create Date: 2023-10-26 07:00:47.680453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c8ff94028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('daily', sa.Boolean(), nullable=True),
    sa.Column('weekly', sa.Boolean(), nullable=True),
    sa.Column('monthly', sa.Boolean(), nullable=True),
    sa.Column('yearly', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('habit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_entries_habit_id_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_performed_date', sa.String(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['habit_entries.id'], name=op.f('fk_entry_dates_entry_id_habit_entries')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_dates')
    op.drop_table('habit_entries')
    op.drop_table('users')
    op.drop_table('habits')
    # ### end Alembic commands ###
