"""initial migration

Revision ID: ec4eac9de156
Revises: 
Create Date: 2023-10-23 14:26:34.766107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4eac9de156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weekly_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dailyHabit_id', sa.Integer(), nullable=True),
    sa.Column('weeklyHabit_id', sa.Integer(), nullable=True),
    sa.Column('monthlyHabit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dailyHabit_id'], ['daily_habits.id'], name=op.f('fk_entries_dailyHabit_id_daily_habits')),
    sa.ForeignKeyConstraint(['monthlyHabit_id'], ['monthly_habits.id'], name=op.f('fk_entries_monthlyHabit_id_monthly_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entries_user_id_users')),
    sa.ForeignKeyConstraint(['weeklyHabit_id'], ['weekly_habits.id'], name=op.f('fk_entries_weeklyHabit_id_weekly_habits')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('weekly_habits')
    op.drop_table('users')
    op.drop_table('monthly_habits')
    op.drop_table('daily_habits')
    # ### end Alembic commands ###
